<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: sublime text | Hello (forgotten) world]]></title>
  <link href="http://tech.aquarite.info/blog/categories/sublime-text/atom.xml" rel="self"/>
  <link href="http://tech.aquarite.info/"/>
  <updated>2014-11-24T08:34:15+09:00</updated>
  <id>http://tech.aquarite.info/</id>
  <author>
    <name><![CDATA[Mei Akizuru]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[YosemiteでSublime Text 3 + LaTeXToolsを使ったらPDF出てこない話]]></title>
    <link href="http://tech.aquarite.info/blog/2014/10/17/sublime-latex-yosemite/"/>
    <updated>2014-10-17T17:56:46+09:00</updated>
    <id>http://tech.aquarite.info/blog/2014/10/17/sublime-latex-yosemite</id>
    <content type="html"><![CDATA[<p>覚え書き。</p>

<p>今日公開されたMac OS X Yosemite (10.10)に早速更新したところ、Sublime Text 3 + LaTeXToolsの環境でLaTeXをビルドしてもPDFが出力されなくなった。</p>

<p>この問題はYosemiteがbetaの時点でアップグレードして報告した猛者がいた。<a href="https://github.com/SublimeText/LaTeXTools/issues/401">LaTeXTools on OS X 10.10 · Issue #401 · SublimeText/LaTeXTools</a></p>

<blockquote><p>opened this issue on 5 Jun</p></blockquote>

<p>（白目）</p>

<p>症状としては上述の通り。ビルドを実行したときにコンソールへ吐き出されているログはこんな感じ。</p>

<pre><code>Welcome to thread Thread-13
['latexmk', '-cd', '-e', "$latex = 'uplatex %O -interaction=nonstopmode -synctex=1 %S'", '-e', "$biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B'", '-e', "$bibtex = 'upbibtex %O %B'", '-e', "$makeindex = 'makeindex %O -o %D %S'", '-e', "$dvipdf = 'dvipdfmx %O -o %D %S'", '-f', '-norc', '-gg', '-pdfdvi', 'report.tex']
Finished normally
12
Exception in thread Thread-13:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/mayth/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/makePDF.py", line 147, in run
    data = open(self.caller.tex_base + ".log", 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mayth/Documents/report.log'
</code></pre>

<p><code>report.{pdf,log}</code>。察して。</p>

<p>それはともかく、どうやらこれは<a href="https://github.com/SublimeText/LaTeXTools/issues/401#issuecomment-59058434">YosemiteでデフォルトのPATHの値が変わっているのが原因</a>らしい。そこで、肝心のコマンドを呼んでいるところでPATHを追加してあげればよい。</p>

<p><a href="https://github.com/SublimeText/LaTeXTools/issues/401#issuecomment-59080557">LaTeXTools on OS X 10.10 · Issue #401 · SublimeText/LaTeXTools</a>から引用すると</p>

<blockquote><p>proc = subprocess.Popen(cmd, stderr=subprocess.STDOUT, stdout=subprocess.PIPE,
env=os.environ)</p></blockquote>

<p>これは<code>makePDF.py</code>の中に含まれている。Macでは<code>makePDF.py</code>は以下のパスにある。</p>

<pre><code>$HOME/Library/Application Support/Sublime Text 3/Packages/LaTeXTools/
</code></pre>

<p>パス辿るのが面倒ならPreferences -> Browse Packagesを使えばPackagesフォルダがFinderで開かれるので、その中のLaTeXToolsを見ると存在するはず。</p>

<p>現時点では当該の記述は95行目にある。その行に上記引用のように、<code>env=os.environ</code>を追記すると上手く動くようになった。</p>
]]></content>
  </entry>
  
</feed>
